Repository FRONTENDBOOTCAMP-13th/Final-03-SEMO, pull requests merged in 2025-07, with the labels that each got.

#2 init/custom.css
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/globals.css
  src/styles/custom.css
Labels: 📗MVP_1, 💄style

#11 Feat/buy page
  .gitignore
  package-lock.json
  src/app/layout.tsx
  src/app/school/buyMarket/itemSection.tsx
  src/app/school/buyMarket/new/page.tsx
  src/app/school/buyMarket/page.tsx
  src/app/school/buyMarket/postId/page.tsx
Labels: ✨ feature, 📗MVP_1, 🎉 init

#13 Feat/mypage
  src/app/school/myPage/(settings)/account/page.tsx
  src/app/school/myPage/(settings)/app-info/page.tsx
  src/app/school/myPage/(settings)/notifications/page.tsx
  src/app/school/myPage/_components/EmptyState.tsx
  src/app/school/myPage/_components/ItemCard.tsx
  src/app/school/myPage/_components/TabNavigation.tsx
  src/app/school/myPage/layout.tsx
  src/app/school/myPage/my-post/page.tsx
  src/app/school/myPage/page.tsx
  src/app/school/myPage/review-to-write/page.tsx
  src/app/school/myPage/wishlist/page.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
Labels: ✨ feature, 📗MVP_1, 🎉 init

#15 Feat/market page
  src/app/layout.tsx
  src/app/school/buyMarket/postId/page.tsx
  src/app/school/market/edit/page.tsx
  src/app/school/market/itemSection.tsx
  src/app/school/market/new/page.tsx
  src/app/school/market/page.tsx
  src/app/school/market/postId/page.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/PopUp.tsx
  src/components/common/Search.tsx
Labels: ✨ feature, 📗MVP_1

#16 feat: onBorder, login, signup
  public/assets/backArrow.svg
  public/assets/google.svg
  public/assets/kakao.svg
  public/assets/unistuffLogo.svg
  src/app/(auth)/_components/BackButton.tsx
  src/app/(auth)/_components/Button.tsx
  src/app/(auth)/_components/Input.tsx
  src/app/(auth)/_components/Logo.tsx
  src/app/(auth)/_components/LogoLow.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/onBoarding/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/layout.tsx
Labels: ✨ feature

#18 Feat/chat-sol
  package-lock.json
  package.json
  public/assets/defaultimg.png
  src/app/layout.tsx
  src/app/school/chat/chatRoom/page.tsx
  src/app/school/chat/chatRoom/useChatSoket.ts
  src/app/school/chat/chatRoom/useChatStore.ts
  src/app/school/chat/components/chatBubble/page.tsx
  src/app/school/chat/components/chatBubbleList/page.tsx
  src/app/school/chat/components/chatHeader/page.tsx
  src/app/school/chat/components/chatRoomItem/page.tsx
  src/app/school/chat/components/inputChat/page.tsx
  src/app/school/chat/components/popup/page.tsx
  src/app/school/chat/components/productInfo/page.tsx
  src/app/school/chat/components/search/page.tsx
  src/app/school/chat/components/tradeComplete/page.tsx
  src/app/school/chat/components/tradeInfoBox/page.tsx
  src/app/school/chat/page.tsx
Labels: ✨ feature

#23 Feat/reviewpage siwoon
  package-lock.json
  package.json
  src/app/school/myPage/_components/EmptyState.tsx
  src/app/school/myPage/_components/InputField.tsx
  src/app/school/myPage/_components/ItemCard.tsx
  src/app/school/myPage/_components/Pagination.tsx
  src/app/school/myPage/_components/ReviewCard.tsx
  src/app/school/myPage/_components/SaveFloatingButton.tsx
  src/app/school/myPage/_components/SectionHeader.tsx
  src/app/school/myPage/_components/TabNavigation.tsx
  src/app/school/myPage/_hooks/pagination/README.md
  src/app/school/myPage/_hooks/pagination/usePagination.tsx
  src/app/school/myPage/_hooks/pagination/useResponsivePagination.tsx
  src/app/school/myPage/data/postData.ts
  src/app/school/myPage/data/reviewsData.ts
  src/app/school/myPage/data/wishlistData.ts
  src/app/school/myPage/layout.tsx
  src/app/school/myPage/my-post/page.tsx
  src/app/school/myPage/page.tsx
  src/app/school/myPage/review-to-write/page.tsx
  src/app/school/myPage/wishlist/page.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
Labels: ✨ feature, 📗MVP_1

#27 Feat/settingpage
  src/app/school/myPage/(history)/my-post/page.tsx
  src/app/school/myPage/(history)/review-to-write/page.tsx
  src/app/school/myPage/(history)/wishlist/page.tsx
  src/app/school/myPage/(settings)/account/page.tsx
  src/app/school/myPage/(settings)/account/utils/validation.ts
  src/app/school/myPage/(settings)/app-info/page.tsx
  src/app/school/myPage/(settings)/logout/page.tsx
  src/app/school/myPage/(settings)/notifications/page.tsx
  src/app/school/myPage/_components/InputField.tsx
  src/app/school/myPage/_components/SaveFloatingButton.tsx
  src/app/school/myPage/_components/SectionHeader.tsx
  src/app/school/myPage/_components/ToggleCard.tsx
  src/app/school/myPage/page.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
Labels: ✨ feature, 📗MVP_1, 💄style

#32 Feat/accountapi
  package-lock.json
  src/app/school/myPage/(settings)/account/page.tsx
  src/app/school/myPage/(settings)/app-info/page.tsx
  src/app/school/myPage/API_INTEGRATION_GUIDE.md
  src/app/school/myPage/_hooks/useMyPageApi.ts
  src/app/school/myPage/_services/apiService.ts
  src/app/school/myPage/_test/ApiTestComponent.tsx
  src/app/school/myPage/_types/user.ts
  src/app/school/myPage/page.tsx
Labels: ✨ feature, 🔌 API, 🧹 refactor, 📗MVP_1

#34 Feat/dynamicChat-sol
  src/app/school/chat/chatId/page.tsx
  src/app/school/chat/chatRoom/page.tsx
  src/app/school/chat/chatRoom/useChatSoket.ts
  src/app/school/chat/chatRoom/useChatStore.ts
  src/app/school/chat/components/chatBubble/page.tsx
  src/app/school/chat/components/chatBubbleList/page.tsx
  src/app/school/chat/components/inputChat/page.tsx
  src/app/school/chat/createChatPost/page.tsx
  src/app/school/chat/page.tsx
  src/app/school/sellMarket/new/page.tsx
  src/app/school/sellMarket/page.tsx
  src/app/school/sellMarket/postId/page.tsx
Labels: ✨ feature, 🔌 API, 🧹 refactor, 📗MVP_1, 📕MVP_2

#46 🐛 fix: localStorage token
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/signup/complete/completeForm.tsx
Labels: 🐛 bug, 🔌 API, ⚙️ backend

#56 Feat/mail code min
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/onBoarding/onBoardingForm.tsx
  src/app/(auth)/signup/complete/completeForm.tsx
  src/app/(auth)/signup/password/pwForm.tsx
  src/app/(auth)/signup/signupForm.tsx
  src/lib/actions/checkDuplicate.ts
  src/lib/actions/login.ts
  src/lib/actions/signup.ts
  src/lib/useAuthGuard.ts
  src/store/userStore.ts
  src/types/user.ts
Labels: ✨ feature, 🔌 API, 🔧 enhancement, 🧹 refactor, 📕MVP_2

#62 Feat/logout min
  src/app/api/auth/logout.ts
  src/app/school/myPage/(settings)/logout/page.tsx
  src/data/actions/file.ts
  src/lib/actions/logout.ts
Labels: ✨ feature, 🔌 API, 🔧 enhancement, ⚙️ backend, 📕MVP_2

#70 Refactor/user data hun
  src/app/school/home/_components/HeroSection.tsx
  src/app/school/home/_components/HomeHeader.tsx
  src/app/school/home/page.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentDeleteForm.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentNew.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostLikeButton.tsx
  src/app/school/market/[marketType]/_components/MarketPageHeader.tsx
  src/app/school/market/[marketType]/_components/MarketTagNav.tsx
  src/app/school/market/[marketType]/_components/PostForm.tsx
  src/app/school/market/[marketType]/itemSection.tsx
  src/app/school/market/[marketType]/page.tsx
  src/components/common/FloatingButton.tsx
Labels: 🐛 bug, 🔧 enhancement, 🧹 refactor, 📕MVP_2

#72 Feat/kakao api min
  src/app/(auth)/_components/Button.tsx
  src/app/(auth)/_components/PasswordInput.tsx
  src/app/(auth)/login/kakao/kakaoForm.tsx
  src/app/(auth)/login/kakao/page.tsx
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/signup/complete/completeForm.tsx
  src/app/(auth)/signup/password/pwForm.tsx
  src/lib/actions/kakao.ts
  src/store/userStore.ts
  src/types/user.ts
Labels: ✨ feature, 🐛 bug, 🔌 API, 🔧 enhancement, 🧹 refactor, ⚙️ backend, 📕MVP_2

#77 Feat/control chatroom sol
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/inputChat.tsx
Labels: ✨ feature, 🐛 bug, 🧹 refactor, 📕MVP_2, 🗑️ Remove

#88 Feat/joinPrivateServer-sol
  package-lock.json
  package.json
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/chatBubbleList.tsx
  src/app/school/chat/components/chatHeader.tsx
  src/app/school/chat/components/chatStartBtn.tsx
  src/app/school/chat/components/inputChat.tsx
  src/app/school/chat/components/popup.tsx
  src/app/school/chat/components/productInfo.tsx
  src/app/school/chat/components/tradeCheck.tsx
Labels: ✨ feature, 🐛 bug, 🔌 API, 📘MVP_3

#89 Fix/mpv3bug-min
  src/app/(auth)/_components/Button.tsx
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/signup/complete/completeForm.tsx
  src/app/(auth)/signup/password/pwForm.tsx
  src/app/(auth)/signup/signupForm.tsx
  src/app/layout.tsx
  src/components/common/globalSocketManager.tsx
  src/lib/useAuthGuard.ts
  src/store/userStore.ts
Labels: 🐛 bug, 🔧 enhancement, 🧹 refactor, 📘MVP_3

#95 feat/bruno-siwoon
  api/bruno/03_team_test/bruno.json
  api/bruno/03_team_test/collection.bru
  api/bruno/03_team_test/environments/team_3.bru
  api/bruno/03_team_test/게시판/folder.bru
  api/bruno/03_team_test/게시판/게시글 등록.bru
  api/bruno/03_team_test/게시판/게시글 상세.bru
  api/bruno/03_team_test/게시판/내 게시물 목록 조회.bru
  api/bruno/03_team_test/게시판/전체 게시글 목록.bru
  api/bruno/03_team_test/상품/folder.bru
  api/bruno/03_team_test/상품/구매 목록 조회.bru
  api/bruno/03_team_test/상품/북마크/folder.bru
  api/bruno/03_team_test/상품/북마크/북마크 목록 조회.bru
  api/bruno/03_team_test/상품/북마크/북마크 추가.bru
  api/bruno/03_team_test/상품/상품 구매.bru
  api/bruno/03_team_test/상품/상품 등록.bru
  api/bruno/03_team_test/상품/상품 목록 조회.bru
  api/bruno/03_team_test/상품/상품 수정.bru
  api/bruno/03_team_test/상품/판매 상품 목록 조회.bru
  api/bruno/03_team_test/상품/후기/folder.bru
  api/bruno/03_team_test/상품/후기/구매 후기 등록.bru
  api/bruno/03_team_test/상품/후기/내 구매 후기 목록.bru
  api/bruno/03_team_test/상품/후기/상품 구매 후기 목록.bru
  api/bruno/03_team_test/시스템/folder.bru
  api/bruno/03_team_test/시스템/다운로드.bru
  api/bruno/03_team_test/시스템/이미지 링크.bru
  api/bruno/03_team_test/시스템/파일 업로드.bru
  api/bruno/03_team_test/회원/folder.bru
  api/bruno/03_team_test/회원/로그인.bru
  api/bruno/03_team_test/회원/회원 가입.bru
  api/bruno/03_team_test/회원/회원 목록 조회.bru
  api/bruno/03_team_test/회원/회원 정보 수정.bru
  api/bruno/03_team_test/회원/회원 정보 조회 (모든 속성).bru
  api/bruno/03_team_test/회원/회원 정보 조회(모든 속성).bru
Labels: 🔌 API
