Repository FRONTENDBOOTCAMP-13th/Final-03-SEMO, pull requests merged in 2025-08, with the labels that each got.

#103 Feat/initialpage siwoon
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/custom.css
  src/components/OnboardingSlider.tsx
Labels: 📘MVP_3, 💄style

#105 Bug/gatheringtab siwoon
  src/app/school/myPage/(history)/my-post/page.tsx
  src/app/school/myPage/(history)/wishlist/page.tsx
  src/app/school/myPage/_components/ItemCard.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
  src/data/functions/myPage.ts
  src/lib/hooks/useMyPosts.ts
  src/lib/imageService.ts
  src/lib/utils/postConverter.ts
Labels: 🐛 bug, 🔧 enhancement, 📘MVP_3

#104 Feat/findAuth-min
  src/app/(auth)/_components/CodeInput.tsx
  src/app/(auth)/_components/PasswordInput.tsx
  src/app/(auth)/find/id/page.tsx
  src/app/(auth)/find/pw/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/kakao/page.tsx
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/onBoarding/onBoardingForm.tsx
  src/app/(auth)/signup/code/page.tsx
  src/app/(auth)/signup/complete/completeForm.tsx
  src/app/(auth)/signup/password/pwForm.tsx
  src/app/(auth)/signup/signupForm.tsx
  src/app/api/auth/logout.ts
  src/app/api/auth/logout/route.ts
  src/app/layout.tsx
  src/app/styles/custom.css
  src/components/ui/Button.tsx
  src/components/ui/Input.tsx
  src/lib/actions/findId.ts
  src/lib/actions/findPw.ts
  src/lib/actions/logout.ts
  src/lib/actions/signup.ts
  src/lib/sendVerificationCode.ts
  src/store/findStore.ts
  src/store/userStore.ts
Labels: 🎨 UI/UX, ✨ feature, 🐛 bug, 🔌 API, 🔧 enhancement, 🧹 refactor, 📘MVP_3, 💄style

#107 bug/layout-siwoon
  src/app/layout.tsx
Labels: 🐛 bug

#109 Refactor/performanceOptimization
  next.config.ts
  src/app/school/home/_components/HomeHeader.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostContent.tsx
  src/app/school/market/[marketType]/[postId]/edit/page.tsx
  src/app/school/market/[marketType]/page.tsx
  src/app/school/market/[marketType]/search/page.tsx
  src/app/school/market/_components/MarketPageHeader.tsx
  src/app/school/market/_components/MarketSearch.tsx
  src/app/school/market/_components/MarketTagNav.tsx
  src/app/school/market/_components/_PostComponents/GroupPurchaseForm.tsx
  src/app/school/market/_components/_PostComponents/PostForm.tsx
  src/app/school/market/_components/_PostComponents/ProductDesc.tsx
  src/app/school/market/_components/_PostComponents/imgUpdate.tsx
  src/app/school/market/loading.tsx
  src/components/ui/Sekleton.tsx
  src/types/file.ts
Labels: 🐛 bug, 🔧 enhancement, 🧹 refactor, 📘MVP_3

#112 Feat/chat room list sol
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/chatRoomItem.tsx
  src/app/school/chat/components/tradeCheck.tsx
  src/app/school/chat/createChatPost/page.tsx
  src/app/school/chat/page.tsx
  src/app/school/home/_components/HomeHeader.tsx
  src/components/common/PopUp.tsx
Labels: ✨ feature, 🔌 API, 🔧 enhancement, 🧹 refactor, 📘MVP_3

#116 Merge/developToMainThird
  src/app/(auth)/login/loginForm.tsx
  src/app/school/home/page.tsx
  src/app/school/market/[marketType]/page.tsx
  src/app/school/myPage/(history)/review-to-write/page.tsx
  src/app/school/myPage/(settings)/account/AccountForm.tsx
  src/app/school/myPage/page.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
  src/components/ui/SaveFloatingButton.tsx
  src/data/functions/myPage.ts
  src/lib/imageService.ts
  src/lib/utils/postConverter.ts
Labels: 📘MVP_3

#120 Refactor/final deployment hun
  src/app/api/market/functions/post.ts
  src/app/school/home/_components/HomeHeader.tsx
  src/app/school/market/_components/_PostComponents/PostForm.tsx
  src/app/school/market/_components/_PostComponents/ProductDesc.tsx
  src/data/actions/post.ts
Labels: 🔧 enhancement, 🧹 refactor, 📘MVP_3

#125 Refactor/chat refactor sol
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/components/chatBubble.tsx
  src/app/school/chat/components/chatBubbleList.tsx
  src/app/school/chat/components/chatRoomItem.tsx
  src/app/school/chat/components/inputChat.tsx
  src/app/school/chat/page.tsx
  src/types/post.ts
Labels: ✨ feature, 🐛 bug, 🔌 API

#124 feat/signupBar-min
  package-lock.json
  package.json
  src/app/(auth)/_components/BackButton.tsx
  src/app/(auth)/_components/SignupBar.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/signup/signupForm.tsx
  src/app/layout.tsx
Labels: ✨ feature, 🧹 refactor, 📘MVP_3, 💄style

#132 🐛 fix: layout 하단 패딩값 롤백
  src/app/layout.tsx
Labels: 🐛 bug, 📘MVP_3

#133 Feat/userprofile siwoon
  api/bruno/03_team_test/게시판/내 게시물 목록 조회.bru
  api/bruno/03_team_test/상품/구매 목록 조회.bru
  api/bruno/03_team_test/시스템/파일 업로드.bru
  api/bruno/03_team_test/회원/로그인.bru
  api/bruno/03_team_test/회원/회원 목록 조회.bru
  api/bruno/03_team_test/회원/회원 정보 조회(모든 속성).bru
  src/app/school/myPage/(settings)/account/AccountForm.tsx
  src/app/school/myPage/page.tsx
  src/app/school/user/[id]/_components/ProductCard.tsx
  src/app/school/user/[id]/_components/UserPostList.tsx
  src/app/school/user/[id]/_components/UserProfileContainer.tsx
  src/app/school/user/[id]/_components/UserProfileHeader.tsx
  src/app/school/user/[id]/_components/UserRating.tsx
  src/app/school/user/[id]/_components/UserReviewList.tsx
  src/app/school/user/[id]/page.tsx
  src/app/school/user/layout.tsx
  src/data/functions/myPage.ts
  src/data/functions/sellerReviews.ts
Labels: 🎨 UI/UX, ✨ feature, 📘MVP_3, 💄style

#136 Bug/market sell preview
  src/app/school/home/_components/ItemPreview.tsx
  src/app/school/home/page.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentItem.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostContent.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostLikeButton.tsx
  src/types/post.ts
Labels: 🔧 enhancement, 🧹 refactor, 📘MVP_3

#138 Refactor/A11y
  src/app/school/home/_components/HeroSection.tsx
  src/app/school/home/_components/HomeHeader.tsx
  src/app/school/home/_components/ItemPreview.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentDeleteForm.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentItem.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentNew.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostActions.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostContent.tsx
  src/app/school/market/_components/MarketSearch.tsx
  src/app/school/market/_components/_PostComponents/PostForm.tsx
  src/app/school/market/_components/_PostComponents/Product.tsx
  src/app/school/market/_components/_PostComponents/ProductDesc.tsx
  src/app/school/market/groupPurchase/new/page.tsx
Labels: 🧹 refactor, 📘MVP_3

#140 refactor/socket-sol
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/chatBubble.tsx
  src/app/school/chat/components/inputChat.tsx
  src/app/school/chat/components/productInfo.tsx
  src/app/school/chat/components/search.tsx
  src/app/school/chat/components/tradeCheck.tsx
  src/app/school/chat/components/tradeComplete.tsx
  src/app/school/chat/page.tsx
  src/components/common/PopUp.tsx
Labels: ✨ feature, 🐛 bug, 🔌 API

#143 Refactor/chat sol
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/components/chatBubble.tsx
  src/app/school/chat/page.tsx
Labels: 🐛 bug, 🔌 API, 🔧 enhancement

#146 merge/developToMainFifth
  api/bruno/03_team_test/게시판/내 게시물 목록 조회.bru
  api/bruno/03_team_test/상품/구매 목록 조회.bru
  api/bruno/03_team_test/시스템/파일 업로드.bru
  api/bruno/03_team_test/회원/로그인.bru
  api/bruno/03_team_test/회원/회원 목록 조회.bru
  api/bruno/03_team_test/회원/회원 정보 조회(모든 속성).bru
  src/app/api/chat/useChatSoket.ts
  src/app/layout.tsx
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/chatBubble.tsx
  src/app/school/chat/components/inputChat.tsx
  src/app/school/chat/components/productInfo.tsx
  src/app/school/chat/components/search.tsx
  src/app/school/chat/components/tradeCheck.tsx
  src/app/school/chat/components/tradeComplete.tsx
  src/app/school/chat/page.tsx
  src/app/school/home/_components/HeroSection.tsx
  src/app/school/home/_components/HomeHeader.tsx
  src/app/school/home/_components/ItemPreview.tsx
  src/app/school/home/page.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentDeleteForm.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentItem.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentNew.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostActions.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostContent.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostLikeButton.tsx
  src/app/school/market/_components/MarketSearch.tsx
  src/app/school/market/_components/_PostComponents/PostForm.tsx
  src/app/school/market/_components/_PostComponents/Product.tsx
  src/app/school/market/_components/_PostComponents/ProductDesc.tsx
  src/app/school/market/groupPurchase/new/page.tsx
  src/app/school/myPage/(settings)/account/AccountForm.tsx
  src/app/school/myPage/page.tsx
  src/app/school/user/[id]/_components/ProductCard.tsx
  src/app/school/user/[id]/_components/UserPostList.tsx
  src/app/school/user/[id]/_components/UserProfileContainer.tsx
  src/app/school/user/[id]/_components/UserProfileHeader.tsx
  src/app/school/user/[id]/_components/UserRating.tsx
  src/app/school/user/[id]/_components/UserReviewList.tsx
  src/app/school/user/[id]/page.tsx
  src/app/school/user/layout.tsx
  src/components/common/PopUp.tsx
  src/data/functions/myPage.ts
  src/data/functions/sellerReviews.ts
  src/types/post.ts
Labels: 🔧 enhancement

#148 Refactor/qaChat
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/chatBubble.tsx
  src/app/school/chat/page.tsx
  src/app/school/user/[id]/page.tsx
Labels: 🐛 bug, 🔌 API, 🔧 enhancement

#156 Refactor/onboardingPatch-min
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/signup/code/page.tsx
  src/app/(auth)/signup/complete/completeForm.tsx
  src/app/school/layout.tsx
  src/app/school/myPage/(settings)/kakaoSetting/page.tsx
  src/components/ui/Input.tsx
  src/lib/AuthRedirectHandler.tsx
  src/lib/actions/signup.ts
  src/lib/useAuthGuard.ts
  src/lib/useRequireProfile.ts
  src/store/userStore.ts
  src/types/user.ts
Labels: ✨ feature, 🐛 bug, 🧹 refactor, 📘MVP_3

#154 Design/onboarding siwoon
  src/app/onBoarding/OnboardingSliderForm.tsx
  src/app/onBoarding/page.tsx
  src/app/page.tsx
  src/app/school/myPage/(history)/my-post/page.tsx
  src/app/school/myPage/(history)/review-to-write/page.tsx
  src/app/school/myPage/(history)/wishlist/page.tsx
  src/app/school/myPage/(settings)/account/page.tsx
  src/app/school/myPage/(settings)/app-info/page.tsx
  src/app/school/myPage/(settings)/logout/page.tsx
  src/app/school/myPage/(settings)/notifications/page.tsx
  src/app/school/myPage/page.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
  src/app/school/user/[id]/_components/UserProfileContainer.tsx
  src/app/school/user/[id]/page.tsx
  src/components/SplashScreenForm.tsx
  src/lib/utils/postConverter.ts
  src/types/myPageApi.ts
Labels: 🎨 UI/UX, 💄style

#157 Refactor/qa hun
  src/app/api/market/functions/post.ts
  src/app/school/home/_components/ItemPreview.tsx
  src/app/school/home/page.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentDeleteForm.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentItem.tsx
  src/app/school/market/[marketType]/[postId]/_components/CommentList.tsx
  src/app/school/market/[marketType]/[postId]/_components/PostContent.tsx
  src/app/school/market/[marketType]/[postId]/page.tsx
  src/app/school/market/[marketType]/itemSection.tsx
  src/app/school/market/_components/MarketTagNav.tsx
  src/app/school/market/_components/_PostComponents/Countdown.tsx
  src/app/school/market/groupPurchase/page.tsx
  src/app/styles/custom.css
Labels: 🧹 refactor, 📘MVP_3, 💄style

#162 Bug/mypage
  src/app/school/myPage/(history)/wishlist/page.tsx
  src/app/school/myPage/(settings)/account/AccountForm.tsx
  src/app/school/myPage/(settings)/notifications/page.tsx
  src/app/school/user/[id]/_components/UserPostList.tsx
Labels: 🐛 bug

#163 Refactor/chat file
  src/app/api/chat/useChatSoket.ts
  src/app/school/chat/[id]/page.tsx
  src/app/school/chat/components/chatBubble.tsx
  src/app/school/chat/components/chatBubbleList.tsx
  src/app/school/chat/components/inputChat.tsx
  src/app/school/chat/components/tradeCheck.tsx
  src/app/school/chat/components/tradeComplete.tsx
  src/app/school/myPage/(history)/review-to-write/ReviewToWriteClient.tsx
  src/app/school/myPage/write-review/[id]/page.tsx
  src/app/school/user/[id]/_components/UserProfileContainer.tsx
  src/app/school/user/[id]/page.tsx
  src/components/common/globalSocketManager.tsx
  src/data/functions/myPage.ts
  src/store/useChatStore.ts
  src/types/myPageUser.ts
Labels: 🐛 bug, 🧹 refactor, 📘MVP_3

#168 Fix/kakao route min
  src/app/(auth)/login/kakao/kakaoForm.tsx
  src/app/(auth)/login/kakao/page.tsx
  src/app/(auth)/signup/code/page.tsx
  src/app/layout.tsx
  src/app/onBoarding/OnboardingSliderForm.tsx
  src/lib/AuthRedirectHandler.tsx
  src/store/userStore.ts
Labels: 🐛 bug, 🔧 enhancement, 📘MVP_3

#184 Fix/mvp4 bug
  src/app/(auth)/_components/LogoLow.tsx
  src/app/(auth)/find/id/idForm.tsx
  src/app/(auth)/find/id/page.tsx
  src/app/(auth)/layout.client.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/kakao/kakaoForm.tsx
  src/app/(auth)/login/kakao/page.tsx
  src/app/(auth)/login/loginForm.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/code/codeForm.tsx
  src/app/(auth)/signup/code/page.tsx
  src/app/(auth)/signup/complete/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/layout.client.tsx
  src/app/layout.tsx
  src/app/school/myPage/(settings)/kakaoSetting/kakaoSettingForm.tsx
  src/app/school/myPage/(settings)/kakaoSetting/page.tsx
  src/app/school/myPage/(settings)/logout/logoutForm.tsx
  src/app/school/myPage/(settings)/logout/page.tsx
  src/store/userStore.ts
Labels: 🐛 bug

#186 fix/kakaoApiBug
  src/app/(auth)/login/kakao/kakaoForm.tsx
  src/app/(auth)/signup/code/codeForm.tsx
  src/app/(auth)/signup/code/page.tsx
  src/app/school/myPage/(settings)/kakaoSetting/kakaoSettingForm.tsx
  src/app/school/myPage/(settings)/kakaoSetting/page.tsx
Labels: 🐛 bug, 🧹 refactor, 🗑️ Remove
